/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as LoginAdminRouteImport } from './routes/login-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroAlunoRouteImport } from './routes/cadastro-aluno'
import { Route as CadastroAdminRouteImport } from './routes/cadastro-admin'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcessoAlunoRouteImport } from './routes/acesso-aluno'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoIndexRouteImport } from './routes/aluno/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AlunoTarefasRouteImport } from './routes/aluno/tarefas'
import { Route as AlunoRankingRouteImport } from './routes/aluno/ranking'
import { Route as AlunoArsenalRouteImport } from './routes/aluno/arsenal'
import { Route as AlunoAgendaRouteImport } from './routes/aluno/agenda'
import { Route as AdminRankingRouteImport } from './routes/admin/ranking'
import { Route as AdminConteudosRouteImport } from './routes/admin/conteudos'
import { Route as AdminArsenalRouteImport } from './routes/admin/arsenal'
import { Route as AdminAlunosRouteImport } from './routes/admin/alunos'
import { Route as AdminAgendaRouteImport } from './routes/admin/agenda'
import { Route as AdminAcessosRouteImport } from './routes/admin/acessos'
import { Route as AlunoAulasAulaIdRouteImport } from './routes/aluno/aulas.$aulaId'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login-admin',
  path: '/login-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroAlunoRoute = CadastroAlunoRouteImport.update({
  id: '/cadastro-aluno',
  path: '/cadastro-aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroAdminRoute = CadastroAdminRouteImport.update({
  id: '/cadastro-admin',
  path: '/cadastro-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoAlunoRoute = AcessoAlunoRouteImport.update({
  id: '/acesso-aluno',
  path: '/acesso-aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlunoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AlunoTarefasRoute = AlunoTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoRankingRoute = AlunoRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoArsenalRoute = AlunoArsenalRouteImport.update({
  id: '/arsenal',
  path: '/arsenal',
  getParentRoute: () => AlunoRoute,
} as any)
const AlunoAgendaRoute = AlunoAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AlunoRoute,
} as any)
const AdminRankingRoute = AdminRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudosRoute = AdminConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArsenalRoute = AdminArsenalRouteImport.update({
  id: '/arsenal',
  path: '/arsenal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcessosRoute = AdminAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AdminRoute,
} as any)
const AlunoAulasAulaIdRoute = AlunoAulasAulaIdRouteImport.update({
  id: '/aulas/$aulaId',
  path: '/aulas/$aulaId',
  getParentRoute: () => AlunoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-aluno': typeof AcessoAlunoRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/cadastro-admin': typeof CadastroAdminRoute
  '/cadastro-aluno': typeof CadastroAlunoRoute
  '/login': typeof LoginRoute
  '/login-admin': typeof LoginAdminRoute
  '/tarefas': typeof TarefasRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/arsenal': typeof AdminArsenalRoute
  '/admin/conteudos': typeof AdminConteudosRoute
  '/admin/ranking': typeof AdminRankingRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/arsenal': typeof AlunoArsenalRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/aluno/tarefas': typeof AlunoTarefasRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/aluno/aulas/$aulaId': typeof AlunoAulasAulaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-aluno': typeof AcessoAlunoRoute
  '/cadastro-admin': typeof CadastroAdminRoute
  '/cadastro-aluno': typeof CadastroAlunoRoute
  '/login': typeof LoginRoute
  '/login-admin': typeof LoginAdminRoute
  '/tarefas': typeof TarefasRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/arsenal': typeof AdminArsenalRoute
  '/admin/conteudos': typeof AdminConteudosRoute
  '/admin/ranking': typeof AdminRankingRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/arsenal': typeof AlunoArsenalRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/aluno/tarefas': typeof AlunoTarefasRoute
  '/admin': typeof AdminIndexRoute
  '/aluno': typeof AlunoIndexRoute
  '/aluno/aulas/$aulaId': typeof AlunoAulasAulaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-aluno': typeof AcessoAlunoRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRouteWithChildren
  '/cadastro-admin': typeof CadastroAdminRoute
  '/cadastro-aluno': typeof CadastroAlunoRoute
  '/login': typeof LoginRoute
  '/login-admin': typeof LoginAdminRoute
  '/tarefas': typeof TarefasRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/arsenal': typeof AdminArsenalRoute
  '/admin/conteudos': typeof AdminConteudosRoute
  '/admin/ranking': typeof AdminRankingRoute
  '/aluno/agenda': typeof AlunoAgendaRoute
  '/aluno/arsenal': typeof AlunoArsenalRoute
  '/aluno/ranking': typeof AlunoRankingRoute
  '/aluno/tarefas': typeof AlunoTarefasRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/aluno/aulas/$aulaId': typeof AlunoAulasAulaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-aluno'
    | '/admin'
    | '/aluno'
    | '/cadastro-admin'
    | '/cadastro-aluno'
    | '/login'
    | '/login-admin'
    | '/tarefas'
    | '/admin/acessos'
    | '/admin/agenda'
    | '/admin/alunos'
    | '/admin/arsenal'
    | '/admin/conteudos'
    | '/admin/ranking'
    | '/aluno/agenda'
    | '/aluno/arsenal'
    | '/aluno/ranking'
    | '/aluno/tarefas'
    | '/admin/'
    | '/aluno/'
    | '/aluno/aulas/$aulaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-aluno'
    | '/cadastro-admin'
    | '/cadastro-aluno'
    | '/login'
    | '/login-admin'
    | '/tarefas'
    | '/admin/acessos'
    | '/admin/agenda'
    | '/admin/alunos'
    | '/admin/arsenal'
    | '/admin/conteudos'
    | '/admin/ranking'
    | '/aluno/agenda'
    | '/aluno/arsenal'
    | '/aluno/ranking'
    | '/aluno/tarefas'
    | '/admin'
    | '/aluno'
    | '/aluno/aulas/$aulaId'
  id:
    | '__root__'
    | '/'
    | '/acesso-aluno'
    | '/admin'
    | '/aluno'
    | '/cadastro-admin'
    | '/cadastro-aluno'
    | '/login'
    | '/login-admin'
    | '/tarefas'
    | '/admin/acessos'
    | '/admin/agenda'
    | '/admin/alunos'
    | '/admin/arsenal'
    | '/admin/conteudos'
    | '/admin/ranking'
    | '/aluno/agenda'
    | '/aluno/arsenal'
    | '/aluno/ranking'
    | '/aluno/tarefas'
    | '/admin/'
    | '/aluno/'
    | '/aluno/aulas/$aulaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoAlunoRoute: typeof AcessoAlunoRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlunoRoute: typeof AlunoRouteWithChildren
  CadastroAdminRoute: typeof CadastroAdminRoute
  CadastroAlunoRoute: typeof CadastroAlunoRoute
  LoginRoute: typeof LoginRoute
  LoginAdminRoute: typeof LoginAdminRoute
  TarefasRoute: typeof TarefasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-admin': {
      id: '/login-admin'
      path: '/login-admin'
      fullPath: '/login-admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-aluno': {
      id: '/cadastro-aluno'
      path: '/cadastro-aluno'
      fullPath: '/cadastro-aluno'
      preLoaderRoute: typeof CadastroAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-admin': {
      id: '/cadastro-admin'
      path: '/cadastro-admin'
      fullPath: '/cadastro-admin'
      preLoaderRoute: typeof CadastroAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-aluno': {
      id: '/acesso-aluno'
      path: '/acesso-aluno'
      fullPath: '/acesso-aluno'
      preLoaderRoute: typeof AcessoAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/aluno/tarefas': {
      id: '/aluno/tarefas'
      path: '/tarefas'
      fullPath: '/aluno/tarefas'
      preLoaderRoute: typeof AlunoTarefasRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/ranking': {
      id: '/aluno/ranking'
      path: '/ranking'
      fullPath: '/aluno/ranking'
      preLoaderRoute: typeof AlunoRankingRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/arsenal': {
      id: '/aluno/arsenal'
      path: '/arsenal'
      fullPath: '/aluno/arsenal'
      preLoaderRoute: typeof AlunoArsenalRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/aluno/agenda': {
      id: '/aluno/agenda'
      path: '/agenda'
      fullPath: '/aluno/agenda'
      preLoaderRoute: typeof AlunoAgendaRouteImport
      parentRoute: typeof AlunoRoute
    }
    '/admin/ranking': {
      id: '/admin/ranking'
      path: '/ranking'
      fullPath: '/admin/ranking'
      preLoaderRoute: typeof AdminRankingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudos': {
      id: '/admin/conteudos'
      path: '/conteudos'
      fullPath: '/admin/conteudos'
      preLoaderRoute: typeof AdminConteudosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arsenal': {
      id: '/admin/arsenal'
      path: '/arsenal'
      fullPath: '/admin/arsenal'
      preLoaderRoute: typeof AdminArsenalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/acessos': {
      id: '/admin/acessos'
      path: '/acessos'
      fullPath: '/admin/acessos'
      preLoaderRoute: typeof AdminAcessosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/aluno/aulas/$aulaId': {
      id: '/aluno/aulas/$aulaId'
      path: '/aulas/$aulaId'
      fullPath: '/aluno/aulas/$aulaId'
      preLoaderRoute: typeof AlunoAulasAulaIdRouteImport
      parentRoute: typeof AlunoRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAcessosRoute: typeof AdminAcessosRoute
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminArsenalRoute: typeof AdminArsenalRoute
  AdminConteudosRoute: typeof AdminConteudosRoute
  AdminRankingRoute: typeof AdminRankingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcessosRoute: AdminAcessosRoute,
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAlunosRoute: AdminAlunosRoute,
  AdminArsenalRoute: AdminArsenalRoute,
  AdminConteudosRoute: AdminConteudosRoute,
  AdminRankingRoute: AdminRankingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlunoRouteChildren {
  AlunoAgendaRoute: typeof AlunoAgendaRoute
  AlunoArsenalRoute: typeof AlunoArsenalRoute
  AlunoRankingRoute: typeof AlunoRankingRoute
  AlunoTarefasRoute: typeof AlunoTarefasRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
  AlunoAulasAulaIdRoute: typeof AlunoAulasAulaIdRoute
}

const AlunoRouteChildren: AlunoRouteChildren = {
  AlunoAgendaRoute: AlunoAgendaRoute,
  AlunoArsenalRoute: AlunoArsenalRoute,
  AlunoRankingRoute: AlunoRankingRoute,
  AlunoTarefasRoute: AlunoTarefasRoute,
  AlunoIndexRoute: AlunoIndexRoute,
  AlunoAulasAulaIdRoute: AlunoAulasAulaIdRoute,
}

const AlunoRouteWithChildren = AlunoRoute._addFileChildren(AlunoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoAlunoRoute: AcessoAlunoRoute,
  AdminRoute: AdminRouteWithChildren,
  AlunoRoute: AlunoRouteWithChildren,
  CadastroAdminRoute: CadastroAdminRoute,
  CadastroAlunoRoute: CadastroAlunoRoute,
  LoginRoute: LoginRoute,
  LoginAdminRoute: LoginAdminRoute,
  TarefasRoute: TarefasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
